#!/usr/bin/env bash
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "$SOWLIB/pluginutils"
source "$SOWLIB/k8s"

getRequiredValue type "type" PLUGINCONFIGJSON
getRequiredValue name "name" PLUGINCONFIGJSON
getValue step "step" PLUGINCONFIGJSON
getValue namespace "namespace" PLUGINCONFIGJSON
getValueList annotations "annotations" PLUGINCONFIGJSON
getValueList labels "labels" PLUGINCONFIGJSON
K8S_setKubeConfig "$PLUGININSTANCE" "$dir/kubeconfig"

tag_resource()
{
  debug "step = '$step', 1 = '$1'"
  if [[ -z ${step:-""} ]] || [[ "$1" == ${step:-""} ]]; then
    for ann in ${annotations[@]}; do
      exec_cmd kubectl${namespace:+" -n "}${namespace:-} annotate "$type" "$name" "$ann" --overwrite
    done
    for lab in ${labels[@]}; do
      exec_cmd kubectl${namespace:+" -n "}${namespace:-} label "$type" "$name" "$lab" --overwrite
    done
  fi
}

case "$1" in
    deploy) ;&
    delete)
        tag_resource "$1"
        ;;
    *) fail "unsupported action $1"
esac