#!/bin/bash -e
#
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eo pipefail

source "$SOWLIB/pluginutils"

source "$SOW/plugins/git/plugin"

deploy() {
  getRequiredValue ext_name "name" PLUGINCONFIGJSON
  info "Generating manifest for '$ext_name' ..."
  getRequiredValue chart_path "chart_path" PLUGINCONFIGJSON
  getRequiredValue manifest_template "manifest_template" PLUGINCONFIGJSON
  chart_name="chart.tar.b64"
  # create tar file
  (
    cd "$dir/repo/$(dirname "$chart_path")"
    tar -cz $(basename "$chart_path") | base64 > "$dir/$chart_name"
  )
  # replace '<CHART>' in the manifest template with the actual chart
  (
    cd "$dir"
    chart=$(<"$chart_name")
    echo "$manifest_template" | sed -E 's@<CHART>@(( read( "'"$chart_name"'" ) ))@1' | spiff merge - > "manifest.yaml"
  )
}

delete() {
  # only creates files, nothing to do
  verbose "Nothing to do."
}

case "$1" in
    deploy) deploy "$@";;
    delete) delete "$@";;
    *) fail "unsupported action $1"
esac