{
 "title": "Gardener Controller Manager",
 "description": "Dashboard with information about the Gardener Controller Manager.",
 "tags": [ "Gardener" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "controller", "query": "label_values(controller)" },
   { "name": "queue", "label": "Controller Workqueue", "query": "label_values(queue)" },
   {
    "name": "quantile",
    "query": "label_values(garden_cm_workqueue_duration_milliseconds, quantile)"
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller controller worker amount",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "garden_cm_worker_amount{controller=~\"$controller\"}",
       "legendFormat": "{{controller}}"
      }
     ]
    }
   ]
  },
  { "title": "Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Items in Workqueue",
   "type": "graph",
   "description": "Items in a given workqueue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_cm_workqueue_items_total{queue=~\"$queue\"} ",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Average time in queue per item over 5m",
   "type": "graph",
   "description": "How long an item is in the workqueue before being processed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "increase(garden_cm_workqueue_latency_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_latency_milliseconds_count{queue=~\"$queue\"}[5m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Average duration per item over 5m",
   "type": "graph",
   "description": "**Duration**: Time it takes for an item to be processed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "increase(garden_cm_workqueue_duration_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_duration_milliseconds_count{queue=~\"$queue\"}[5m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Rate of workqueue item additions over 5m",
   "type": "graph",
   "description": "Number of workqueue items added per second over the past 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Items added/s" }
   ],
   "targets": [
    {
     "expr": "rate(garden_cm_workqueue_items_adds_total{queue=~\"$queue\"}[5m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Rate of workqueue item retries over 5m",
   "type": "graph",
   "description": "Number of finished workqueue items that are added to the queue again per second over the past 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Items retried/s" }
   ],
   "targets": [
    {
     "expr": "rate(garden_cm_workqueue_retries_total{queue=~\"$queue\"}[5m])",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Latency Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "50th Percentile of time per item spent in $queue workqueue",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 35 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "garden_cm_workqueue_latency_milliseconds{queue=~\"$queue\", quantile=\"0.5\"}"
      }
     ]
    },
    {
     "title": "99th Percentile of time per item spent in $queue workqueue",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 35 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "garden_cm_workqueue_latency_milliseconds{queue=~\"$queue\", quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "Average time in $queue workqueue per item last 5m",
     "type": "singlestat",
     "description": "How long an item is in the workqueue before being processed.",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 35 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "increase(garden_cm_workqueue_latency_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_latency_milliseconds_count{queue=~\"$queue\"}[5m])"
      }
     ]
    },
    {
     "title": "Time in $queue workqueue of each item over the past 5m",
     "type": "heatmap",
     "description": "How long an item is in the workqueue before being processed.",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 35 },
     "repeat": "queue",
     "targets": [
      {
       "expr": "increase(garden_cm_workqueue_latency_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_latency_milliseconds_count{queue=~\"$queue\"}[5m]) ",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "50th Percentile of duration in $queue workqueue",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 36 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "garden_cm_workqueue_duration_milliseconds{queue=~\"$queue\", quantile=\"0.5\"}"
      }
     ]
    },
    {
     "title": "99th Percentile of duration in $queue workqueue",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 36 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "garden_cm_workqueue_duration_milliseconds{queue=~\"$queue\", quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "Average duration in $queue workqueue per item last 5m",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 36 },
     "repeat": "queue",
     "format": "dtdurationms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "increase(garden_cm_workqueue_duration_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_duration_milliseconds_count{queue=~\"$queue\"}[5m])"
      }
     ]
    },
    {
     "title": "Duration of each item added to $queue workqueue over the past 5m",
     "type": "heatmap",
     "description": "Duration: Processing duration in milliseconds of an workqueue item.",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 36 },
     "repeat": "queue",
     "targets": [
      {
       "expr": "increase(garden_cm_workqueue_duration_milliseconds_sum{queue=~\"$queue\"}[5m]) / increase(garden_cm_workqueue_duration_milliseconds_count{queue=~\"$queue\"}[5m]) ",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  }
 ]
}