{
 "title": "Kubernetes Pods",
 "tags": [
  "kubernetes",
  "seed",
  "shoot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_usage_seconds_total, pod_name)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_usage_seconds_total{pod_name=~\"$pod\", container_name!=\"POD\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"$pod\", container_name=~\"$container\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$container\",pod_name=~\"$pod\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])) by (pod_name) ",
     "legendFormat": "{{ pod_name }} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod_name=~\"$pod\"}[1m])) by (pod_name) ",
     "legendFormat": "{{ pod_name }} Sent"
    }
   ]
  },
  {
   "title": "Pod File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\",})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"$pod\", image!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}