{
 "title": "Landscape Availability",
 "description": "Landscape Availability Information",
 "tags": [
  "Landscape",
  "Gardener",
  "Shoot",
  "Seed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "purpose",
    "label": "Cluster Purpose",
    "query": "label_values(garden_shoot_condition, purpose)"
   },
   {
    "name": "iaas",
    "label": "Infrastructure",
    "query": "label_values(garden_shoot_info, iaas)"
   },
   {
    "name": "seed",
    "label": "Seed",
    "query": "label_values(garden_shoot_info{iaas=~\"$iaas\"}, seed)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(garden_shoot_info{iaas=~\"$iaas\", seed=~\"$seed\"}, region)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kube API Server",
   "type": "singlestat",
   "description": "Current Availability of the Kube API Server.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{purpose=\"availability\",job=\"blackbox-apiserver\"}"
    }
   ]
  },
  {
   "title": "Gardener API Server",
   "type": "singlestat",
   "description": "Current Availability of the Gardener API Server.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{purpose=\"availability\", job=\"blackbox-gardener-apiserver\"}"
    }
   ]
  },
  {
   "title": "Gardener Controller Manager",
   "type": "singlestat",
   "description": "Current Availability of the Gardener Controller Manager.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{purpose=\"availability\", job=\"blackbox-gardener-controller-manager\"}"
    }
   ]
  },
  {
   "title": "Gardener Dashboard",
   "type": "singlestat",
   "description": "Current Availability of the Gardener Dashboard.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{purpose=\"availability\", job=\"blackbox-dashboard\"}"
    }
   ]
  },
  {
   "title": "Identity/Dex",
   "type": "singlestat",
   "description": "Current Availability of the Identity/Dex.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{purpose=\"availability\", job=\"blackbox-dex\"}"
    }
   ]
  },
  {
   "title": "Landscape Components Availability (Health Check Responses)",
   "type": "graph",
   "description": "### State Meaning\n1 : Up  \n0 : Down (Http health probe for component failed or returned with unhealthy status code)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Down / Up" }
   ],
   "targets": [
    {
     "expr": "label_replace(probe_success{purpose=\"availability\"}, \"component\", \"$1\", \"job\", \"blackbox-(.*)\")",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Landscape Components Health Check Response Times",
   "type": "graph",
   "description": "Health check response times of the Garden cluster or Gardener components.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ms", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(probe_http_duration_seconds{purpose=\"availability\"}) by (job), \"component\", \"$1\", \"job\", \"blackbox-(.*)\")",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "Shoots and Seeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Shoot/Seed Cluster API Server/ETCD Availability/Health Check",
   "type": "graph",
   "description": "### State Meaning\n1 : Up  \n2 : Progressing (in transition to down)  \n0 :  Down  \n-1 :  Unknown",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "State" }
   ],
   "targets": [
    {
     "expr": "garden_shoot_info{iaas=~\"${iaas:pipe}\",seed=~\"${seed:pipe}\",region=~\"${region:pipe}\"} + on(name, project) garden_shoot_condition{condition=\"APIServerAvailable\", purpose=~\"${purpose:pipe}\"}",
     "legendFormat": "{{project}}/{{name}}"
    }
   ]
  }
 ]
}