apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-grafana-datasources
  namespace: (( values.namespace ))
  labels:
    app: monitoring
    role: grafana
    context: garden
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: Graphite
      orgId: 1
    datasources:
    - name: cluster-prometheus
      type: prometheus
      access: proxy
      url: http://garden-prometheus:80
      basicAuth: false
      isDefault: true
      version: 1
      editable: false