---
apiVersion: v1
kind: Secret
metadata:
  name: garden-grafana-basic-auth
  namespace: (( values.namespace ))
  labels:
    app: monitoring
    role: grafana
    context: garden
data:
  auth: (( base64( .imports.prometheus.export.monitoring_auth ) ))
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: garden-grafana
  namespace: (( values.namespace ))
  labels:
    app: monitoring
    role: grafana
    context: garden
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: garden-grafana-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
spec:
  rules:
  - host: (( .settings.grafana_domain ))
    http:
      paths:
      - backend:
          serviceName: garden-grafana
          servicePort: 80
        path: /
  tls:
  - hosts:
    - (( .settings.grafana_domain ))
    secretName: (( .imports.cert.export.certificate.secret_name ))
