---
imports: (( &temporary ))
landscape: (( &temporary ))

settings:
  certificate:
    name: dashboard-identity-ingress
    domains:
      - (( .landscape.domains.wildcard_ingress_dns ))
      - (( .landscape.dashboard.cname.domain || ~~ ))
    secret_name: identity-dashboard-tls
    namespace: (( landscape.namespace ))

plugins:
  - kubectl: cert
  - -echo: "The export generation waits for the certificate, which may take some time."

cert:
  kubeconfig: (( .landscape.clusters[0].kubeconfig ))
  manifests:
    - apiVersion: cert.gardener.cloud/v1alpha1
      kind: Certificate
      metadata:
        name: (( .settings.certificate.name ))
        namespace: (( .settings.certificate.namespace ))
        annotations:
          cert.gardener.cloud/class: (( imports.cert-controller.export.certClass ))
      spec:
        commonName: (( .landscape.domains.identity_dns ))
        dnsNames: (( .settings.certificate.domains ))
        secretRef:
          name: (( .settings.certificate.secret_name ))
          namespace: (( .settings.certificate.namespace ))
        issuerRef:
          name: (( imports.cert-controller.export.issuerName ))
