---
imports: (( &temporary ))
landscape: (( &temporary ))

settings:
  certificate:
    name: dashboard-identity-ingress
    domains:
      - (( "*." imports.ingress-controller.export.ingress_domain ))
      - (( .landscape.dashboard.cname.domain || ~~ ))
    secret_name: identity-dashboard-tls
    namespace: (( landscape.namespace ))

plugins:
  - kubectl: cert
  - -echo: "The export generation waits for the certificate, which may take some time."

cert:
  kubeconfig: (( .landscape.clusters[0].kubeconfig ))
  manifests:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: (( .settings.certificate.name ))
        namespace: (( .settings.certificate.namespace ))
      spec:
        secretName: (( .settings.certificate.secret_name ))
        renewBefore: 360h # 15d
        dnsNames: (( .settings.certificate.domains ))
        issuerRef:
          name: (( imports.cert-controller.export.issuerName ))
          kind: ClusterIssuer
