#!/usr/bin/env python3

import yaml
import json
import os
from pathlib import Path

dep_file = Path(__file__).resolve().parent.parent / 'dependency-versions.yaml'
dep_name = os.getenv('DEPENDENCY_NAME')
dep_version = os.getenv('DEPENDENCY_VERSION')

if dep_name == 'github.com/gardener/gardener':
    with dep_file.open() as f:
        deps = yaml.safe_load(f)
    
    deps['versions']['gardener']['core']['version'] = dep_version
    
    with dep_file.open(mode='w') as f:
        f.write(json.dumps(deps, indent=2))