#!/usr/bin/env bash

set -e

SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"

TESTRUN_PATH="$SOURCE_PATH/test/testrun.yaml"

mkdir -p /tm
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name testmachinery --key kubeconfig > /tm/kubeconfig

# timeout to 6h
/testrunner run-testrun \
    --tm-kubeconfig-path=/tm/kubeconfig \
    --timeout=21600 \
    --interval=60 \
    -f $TESTRUN_PATH
