#!/usr/bin/env bash
set -e

export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"

TESTRUN_CHART=""
TM_LANDSCAPE="external"
LANDSCAPE=""
ARGUMENTS=""

ARGOUI_ENDPOINT=""
S3_ENDPOINT=""
KIBANA_ENDPOINT=""


for i in "$@"
do
echo $i
case $i in
        -tm-chart=*|--tm-chart=*)
        TESTRUN_CHART="${i#*=}"
        shift
    ;;
        -tm-landscape=*|--tm-landscape=*)
        TM_LANDSCAPE="${i#*=}"
        shift
    ;;
        -landscape=*|--landscape=*)
        LANDSCAPE="${i#*=}"
        shift
    ;;
        --)
        ARGUMENTS="${@:2}"
        break
    ;;
    *)
        # unknown option
        echo "Unkown option ${i#*=}"
        exit 1
    ;;
esac
done

if [[ $TESTRUN_CHART == "" ]]; then
    echo "Required paramter: -tm-chart"
    exit 1
fi
if [[ $TM_LANDSCAPE == "" ]]; then
    echo "Required paramter: -tm-landscape : external | internal"
    exit 1
fi
if [[ $LANDSCAPE == "" ]]; then
    echo "Required paramter: -landscape"
    exit 1
fi

if [[ $TM_LANDSCAPE == "external" ]]; then
    TM_CONFIG_NAME=testmachinery
    S3_ENDPOINT="storage.googleapis.com"
fi
if [[ $TM_LANDSCAPE == "staging" ]]; then
    TM_CONFIG_NAME=testmachinery-staging
    S3_ENDPOINT="storage.googleapis.com"
fi

pushd .
cd $SOURCE_PATH
VERSION=$(git rev-parse HEAD)
popd
GARDENER_VERSION=$(cat $SOURCE_PATH/GARDENER_VERSION)

echo "Testmachinery config name: ${TM_CONFIG_NAME}"
echo "Testmachinery landscape: ${TM_LANDSCAPE}"
echo "Arguments: ${ARGUMENTS}"
echo "Version: ${VERSION}"
echo "Gardener Version: ${GARDENER_VERSION}"

mkdir -p /tm
TM_CLUSTER=/tm/kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name $TM_CONFIG_NAME --key kubeconfig > $TM_CLUSTER

TESTRUN_CHART_PATH="$SOURCE_PATH/test/testruns/$TESTRUN_CHART"
# COMPONENT_DESCRIPTOR_PATH="$COMPONENT_DESCRIPTOR_DIR/component_descriptor"

export KUBECONFIG=$TM_CLUSTER
kubectl cluster-info

# timeout to 6h
/testrunner run-full \
    --tm-kubeconfig-path=$TM_CLUSTER \
    --timeout=21600 \
    --interval=60 \
    --es-config-name=sap_internal \
    --s3-endpoint=$S3_ENDPOINT \
    --s3-ssl=true \
    --testruns-chart-path=$TESTRUN_CHART_PATH \
    --set=gardensetup.version=$VERSION,gardener.version=$GARDENER_VERSION \
    $ARGUMENTS
