job_name: gardener-metrics-exporter
kubernetes_sd_configs:
- role: endpoints
  namespaces:
    names:
    - garden
relabel_configs:
- source_labels: [__meta_kubernetes_service_name]
  regex: gardener-metrics-exporter
  action: keep
metric_relabel_configs:
- source_labels: [ __name__ ]
  regex: ^(garden_projects_status|garden_users_total|garden_shoot_info|garden_shoot_condition|garden_shoot_operation_states|garden_shoot_node_max_total|garden_shoot_node_min_total|garden_shoot_response_duration_milliseconds|garden_shoot_operations_total)$
  action: keep