---
apiVersion: v1 # workaround: extracted from '01-blackbox-exporter-config.yaml' due to unsolved spiff error
kind: Secret
metadata:
  name: garden-blackbox-exporter-probe-secret
  namespace: (( values.namespace ))
  labels:
    app: monitoring
    role: prometheus
    context: garden
data:
  ca.crt: (( base64( values.apiserver_cert.cert ) ))
  apiserver.crt: (( base64( values.apiserver_cert.cert ) ))
  apiserver.key: (( base64( values.apiserver_cert.key ) ))
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-blackbox-exporter-config
  namespace: (( values.namespace ))
  labels:
    app: monitoring
    role: prometheus
    context: garden
data:
  config.yaml: |
    modules:
      tcp_vpn:
        prober: tcp
        timeout: 2s
      http_2xx:
        prober: http
        timeout: 10s
        http:
          headers:
            Accept: "*/*"
            Accept-Language: "en-US"
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
      http_apiserver:
        prober: http
        timeout: 10s
        http:
          headers:
            Accept: "*/*"
            Accept-Language: "en-US"
          tls_config:
            ca_file: "/var/run/secrets/blackbox/ca.crt"
            cert_file: "/var/run/secrets/blackbox/apiserver.crt"
            key_file: "/var/run/secrets/blackbox/apiserver.key"
          preferred_ip_protocol: "ip4"