#! /bin/bash -e

copy_state() {
    mkdir -p $TM_SHARED_PATH/setup
    cp -R ./state $TM_SHARED_PATH/setup
    cp -R ./export $TM_SHARED_PATH/setup
    cp -R ./gen $TM_SHARED_PATH/setup
}

SOURCE_PATH="$(realpath .)"

# change working directory and add garden-setup as crop
# secrets (kubeconfig and gcloud) are mounted to /tmp/garden
cd /tmp/garden
ln -s $SOURCE_PATH ./crop
cp $SOURCE_PATH/test/acre.yaml .

trap copy_state EXIT

sow order -A
sow -Dv deploy -A

cp -R ./export/kube-apiserver/kubeconfig $TM_KUBECONFIG_PATH/gardener.config

copy_state

