#! /bin/bash -e

copy_state() {
    cp -R ./export/kube-apiserver/kubeconfig $TM_KUBECONFIG_PATH/gardener.config
}

SOURCE_PATH="$(realpath .)"

# change working directory and add garden-setup as crop
# secrets (kubeconfig and gcloud) are mounted to /tmp/garden
cd /tmp/garden
ln -s $SOURCE_PATH ./crop
cp $SOURCE_PATH/test/acre.yaml .
cp $TM_KUBECONFIG_PATH/host.config ./kubeconfig

kubectl --kubeconfig=./kubeconfig delete ns garden-setup-state --ignore-not-found

trap copy_state EXIT
sow order -A
sow -Dv deploy -A

copy_state

