#! /bin/bash -e


SOURCE_PATH="$(realpath .)"

# change working directory and add garden-setup as crop
# secrets (kubeconfig and gcloud) are mounted to /tmp/garden
cd /tmp/garden
ln -s $SOURCE_PATH ./crop
cp $SOURCE_PATH/test/acre.yaml .
cp $TM_KUBECONFIG_PATH/host.config ./kubeconfig

sow order -A
sow delete -A

rm -f $TM_KUBECONFIG_PATH/gardener.config
