#! /bin/bash -e

SOURCE_PATH="$(realpath .)"

# change working directory and add garden-setup as crop
# secrets (kubeconfig and gcloud) are mounted to /tmp/garden
cd /tmp/garden
ln -s $SOURCE_PATH ./crop
cp $SOURCE_PATH/test/acre.yaml .

cp -R $TM_KUBECONFIG_PATH/setup/* .

sow order -A
sow delete -A
