#! /bin/bash -e

SOURCE_PATH="$(realpath .)"

# change working directory and add garden-setup as crop
# secrets (kubeconfig and gcloud) are mounted to /tmp/garden
cd /tmp/garden
ln -S $SOURCE_PATH ./crop
cp $SOURCE_PATH/test/acre.yaml .

mv -v $TM_KUBECONFIG_PATH/setup/* .

sow order -A
sow deploy -A

mkdir -p $TM_KUBECONFIG_PATH/setup
cp -R ./state $TM_KUBECONFIG_PATH/setup
cp -R ./export $TM_KUBECONFIG_PATH/setup
cp -R ./gen $TM_KUBECONFIG_PATH/setup

