---
imports: (( &temporary ))
landscape: (( &temporary ))
utilities: (( &temporary ))

plugins:
  - kubectl: grafana

settings:
  grafana_domain: (( "garden-grafana." .imports.ingress-controller.export.ingress_domain ))
  grafana_dashboards_configmap: "garden-grafana-dashboards"

grafana: (( sum[list_files( __ctx.DIR "/manifests" )|[]|s,f|-> s .utilities.kubectl.generate( __ctx.DIR "/manifests/" f, .landscape.clusters[0].kubeconfig, .kubectlconfig )] ))

kubectlconfig:
  <<: (( &temporary ))
  namespace: (( .landscape.namespace ))
  monitoring_versions: (( .landscape.versions.monitoring ))
  settings: (( .settings ))
